name: Fix Code

on:

  push:

    branches:

      - main

jobs:

  fix-code:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

      - name: Setup Node.js

        uses: actions/setup-node@v2

        with:

          node-version: '16'

      - name: Install dependencies

        run: npm install

      - name: Run Code-Fixer

        uses: New-Dev3/code-fixer@v1

        with:

          target-dir: '.' # Change this to the directory containing the code you want to fix

          fixed-dir: './fixed' # Change this to the directory where you want to store the fixed code

          max-retries: 5 # Change this to the maximum number of times to retry the Code-Fixer action

          retry-delay: 30 # Change this to the delay (in seconds) between retries

          ignore-errors: true # Change this to true if you want the action to continue even if errors occur

          fail-on-errors: true # Change this to true if you want the action to fail if errors occur

      - name: Test fixed code

        run: |

          cd ./fixed

          npm test

      - name: Upload fixed code

        uses: actions/upload-artifact@v2

        with:

          name: fixed-code

          path: ./fixed
